{ config, pkgs, lib, ... }:

with lib;
let
  cfg = config.services.tahoe;
in
{
  environment = (mkIf (cfg.nodes != {}) {
    etc = flip mapAttrs' cfg.nodes (node: settings:
      nameValuePair "tahoe-lafs/${node}.cfg" (mkOverride 10 {
        mode = "0444";
        text = ''
          # This configuration is generated by Nix. Edit at your own
          # peril; here be dragons.
          [node]
          nickname = ${settings.nickname}
          tub.port = ${toString settings.tub.port}
          ${optionalString (settings.tub.location != null)
            "tub.location = ${settings.tub.location}"}
          # This is a Twisted endpoint. Twisted Web doesn't work on
          # non-TCP. ~ C.
          web.port = tcp:${toString settings.web.port}
          [client]
          ${optionalString (settings.client.introducer != null)
            "introducer.furl = ${settings.client.introducer}"}
          ${optionalString (settings.client.helper != null)
            "helper.furl = ${settings.client.helper}"}
          shares.needed = ${toString settings.client.shares.needed}
          shares.happy = ${toString settings.client.shares.happy}
          shares.total = ${toString settings.client.shares.total}
          [storage]
          enabled = ${if settings.storage.enable then "true" else "false"}
          reserved_space = ${settings.storage.reservedSpace}
          expire.enabled = true
          expire.mode = age
          [helper]
          enabled = ${if settings.helper.enable then "true" else "false"}
          [sftpd]
          enabled = ${if settings.sftpd.enable then "true" else "false"}
          ${optionalString (settings.sftpd.port != null)
            "port = ${toString settings.sftpd.port}"}
          ${optionalString (settings.sftpd.hostPublicKeyFile != null)
            "host_pubkey_file = ${settings.sftpd.hostPublicKeyFile}"}
          ${optionalString (settings.sftpd.hostPrivateKeyFile != null)
            "host_privkey_file = ${settings.sftpd.hostPrivateKeyFile}"}
          ${optionalString (settings.sftpd.accounts.file != null)
            "accounts.file = ${settings.sftpd.accounts.file}"}
          ${optionalString (settings.sftpd.accounts.url != null)
            "accounts.url = ${settings.sftpd.accounts.url}"}
        '';
      }));
  });
}
